### ISSUE TITLE
Windows 10 compatibility

### ISSUE THREAD

**Issue by sartys** [kidosoft/Morelia#51]
* Morelia version: 0.6.5
* Python version: 2.7
* Operating System: Windows 10

### Description

I went through first initial steps here:
https://pypi.python.org/pypi/Morelia/
until
python -m unittest -v test_acceptance

### What I Did

the command:
c:\Python27\python.exe -m unittest -v test1

the output:
C:\Python27\python.exe -m unittest -v test1
test_addition (test1.Test_test1) ... ERROR

======================================================================
ERROR: test_addition (test1.Test_test1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\lib\unittest\__main__.py", line 12, in <module>
    main(module=None)
  File "c:\Python27\lib\unittest\main.py", line 95, in __init__
    self.runTests()
  File "c:\Python27\lib\unittest\main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "c:\Python27\lib\unittest\runner.py", line 158, in run
    result.printErrors()
  File "c:\Python27\lib\unittest\runner.py", line 108, in printErrors
    self.printErrorList('ERROR', self.errors)
  File "c:\Python27\lib\unittest\runner.py", line 116, in printErrorList
    self.stream.writeln("%s" % err)
  File "c:\Python27\lib\unittest\runner.py", line 24, in writeln
    self.write(arg)
  File "c:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\ufeff' in position 952: character maps to <undefined>

**Comment by izabeera** [comment]
It's not a morelia bug. You have BOM (https://en.wikipedia.org/wiki/Byte_order_mark) char at the beginning of the source code file.

**Comment by sartys** [comment]
Hello Iza,

Thank you for quick reply!
I really like this solution so far!

Removing the BOM definitely fixed the problem, 
but why do you think that this was not a problem?
Are you planning to add Unicode support?

Thanks

**Comment by izabeera** [comment]
Hi sartys,

This is a problem but not in Morelia. In the traceback that you have pasted there is no Morelia code involved.

That is a problem with python2.7 on Windows. If you'll remove Morelia code from your file and use plain unittest to run your code with BOM it will also print error.

I do not use Windows on daily basis but as I recall correctly that bug has been fixed in python3.x.

If you need to use Unicode then the easiest way to use it on Windows and python2.7 is to save file with encoding specification as described here: https://www.python.org/dev/peps/pep-0263/#id8
